# Generated by Django 2.2.28 on 2024-07-19 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xword_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clue',
            old_name='clue',
            new_name='clue_text',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='entry',
            new_name='entry_text',
        ),
    ]
