# Generated by Django 2.2.28 on 2024-07-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xword_data', '0002_auto_20240719_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='byline',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='publisher',
            field=models.CharField(max_length=50),
        ),
    ]
