# Generated by Django 2.2.28 on 2024-07-19 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xword_data', '0003_auto_20240719_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='puzzle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='xword_data.Puzzle'),
        ),
        migrations.AlterField(
            model_name='clue',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xword_data.Entry'),
        ),
    ]
